name: Update Stats Images

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows you to run it manually

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download Stats Card
        run: |
          curl -o github-stats.svg "https://github-readme-stats.vercel.app"
      
      - name: Download Langs Card
        run: |
          curl -o top-langs.svg "https://github-readme-stats.vercel.app"

      - name: Download Streak Card
        run: |
          curl -o streak-stats.svg "https://github-readme-streak-stats.herokuapp.com"

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-stats.svg top-langs.svg streak-stats.svg
          git commit -m "chore: update profile stats images" || exit 0
          git push
