name: Update Stats Images

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download Cards
        run: |
          # A more stable stats provider
          curl -sL "https://github-readme-activity-graph.vercel.app" -o github-stats.svg
          
          # Stable language mirror (only if it returns <svg)
          curl -sL "https://github-readme-stats-git-master-anuraghazra.vercel.app" -o top-langs.svg

          # Reliable Streak Mirror
          curl -sL "https://streak-stats.demolab.com" -o streak-stats.svg

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-stats.svg top-langs.svg streak-stats.svg
          git commit -m "chore: update profile stats images" || exit 0
          git push
